### ISSUE TITLE
 RInAppBilling: Can't find method to get list of purchases

### ISSUE THREAD

**Issue by ZaydelEduard** [WindSekirun/RichUtilsKt#57]
How i can querying list of purchases?

link to docs: http://prntscr.com/jd3ozn

**Comment by WindSekirun** [comment]
you can use [getPurchase()](https://github.com/WindSekirun/RichUtilsKt/blob/master/RichUtils/src/main/java/pyxis/uzuki/live/richutilskt/module/iap/RInAppBilling.kt#L145t) method in RInAppBIlling.

**Comment by ZaydelEduard** [comment]
Oh, I'm sorry.
Thanks
